version: '3'

services:
  node:
    container_name: joys_node
    build: node
    restart: always
    entrypoint: /Joys/start.sh
    volumes:
      - geth_data:/Joys/node:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
    stdin_open: true
    tty: true

volumes:
    geth_data:
      driver: local
